version: '3.9'
services:
    mysql1: 
      image: mysql:8.0 
      container_name: db1
      ports:
          - "3306:3306"  
      environment:   
        MYSQL_ROOT_PASSWORD: admin
      command: --default-authentication-plugin=mysql_native_password  
    node1: 
        build: ./backend
        container_name: n1 
        ports:
          - "8080:8080" 
        volumes:
          - /Users/kanwarsingh/Desktop/Fall 2023/CMPT 353/Project/backend:/usr/src/app 
        depends_on:  
          mysql1:   
            condition: service_started 
        stdin_open: true 
        tty: true
    react1:
        build: ./client
        container_name: r1
        volumes:
          - /Users/kanwarsingh/Desktop/Fall 2023/CMPT 353/Project/client:/usr/src/app
        ports:
          - "3000:3000"
        stdin_open: true 
        tty: true  
